export const optionsTypes= [
    { value: 'bug', label: 'bug' },
    { value: 'dragon', label: 'dragon' },
    { value: 'fairy', label: 'fairy' },
    { value: 'fire', label: 'fire' },
    { value: 'ghost', label: 'ghost' },
    { value: 'ground', label: 'ground' },
    { value: 'normal', label: 'normal' },
    { value: 'pyschic', label: 'pyschic' },
    { value: 'steel', label: 'steel' },
    { value: 'dark', label: 'dark' },
    { value: 'electric', label: 'electric' },
    { value: 'fighting', label: 'fighting' },
    { value: 'flying', label: 'flying' },
    { value: 'grass', label: 'grass' },
    { value: 'ice', label: 'ice' },
    { value: 'poison', label: 'poison' },
    { value: 'rock', label: 'rock' },
    { value: 'water', label: 'water' },
  ];
